version: '3.8'

services:
  app:
    build: .
    container_name: joba-scraper
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mongodb
      - redis
    networks:
      - joba-network

  mongodb:
    image: mongo:5.0
    container_name: joba-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-password}
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - joba-network

  redis:
    image: redis:6.2-alpine
    container_name: joba-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-}
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - joba-network

networks:
  joba-network:
    driver: bridge

volumes:
  mongodb-data:
  redis-data: